=== deterherligt/valg-data/folketingsvalg-135-24-03-2026/Snitfladebeskrivelser/Valgresultater/FV-Valgresultater.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "FV-Valgresultater",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "IndenforParti",
    "UdenforParti",
    "Valgdag",
    "Valgart",
    "FrigivelsesTidspunktUTC",
    "Storkreds",
    "Storkredsnummer",
    "Opstillingskreds",
    "OpstillingskredsDagiId",
    "Kommune",
    "Kommunekode",
    "AfstemningsområdeNummer",
    "AfstemningsområdeDagiId",
    "Afstemningsområde",
    "UgyldigeFremmødteStemmerÅrsager",
    "UgyldigeBrevstemmerÅrsager",
    "Resultatart",
    "AfgivneStemmer",
    "GyldigeStemmer",
    "UgyldigeStemmerUdoverBlanke",
    "BlankeUgyldigeFremmødteStemmer",
    "BlankeUgyldigeBrevstemmer",
    "AfgivneStemmerDifferenceFraForrigeValg",
    "GyldigeStemmerDifferenceFraForrigeValg",
    "UgyldigeStemmerDifferenceFraForrigeValg",
    "BlankeStemmerDifferenceFraForrigeValg",
    "AntalStemmeberettigedeVælgereDifferenceFraForrigeValg",
    "AntalStemmeberettigedeVælgere"
  ],
  "properties": {
    "Valgdag": {
      "type": "string",
      "description": "Dato for valget",
      "format": "date",
      "pattern": "^(0[1-9]|[12][0-9]|3[01])-(0[1-9]|1[0-2])-(\\d{4})$"
    },
    "Valgart": {
      "description": "Navn på valget fx.: Folketingsvalg.",
      "oneOf": [
        {
          "$ref": "#/definitions/Valgart"
        }
      ]
    },
    "FrigivelsesTidspunktUTC": {
      "type": "string",
      "description": "UTC DateTime for filens oprettelse.",
      "format": "date-time",
      "pattern": "^(0[1-9]|[12][0-9]|3[01])-(0[1-9]|1[0-2])-(\\d{4}) (0[0-9]|1[0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9])$"
    },
    "Storkreds": {
      "type": [
        "null",
        "string"
      ],
      "description": "Navn på storkredsen."
    },
    "Storkredsnummer": {
      "type": [
        "integer",
        "null"
      ],
      "description": "Storkredsnummer for storkredsen.",
      "format": "int32"
    },
    "Opstillingskreds": {
      "type": [
        "null",
        "string"
      ],
      "description": "Navn på opstillingskredsen"
    },
    "OpstillingskredsDagiId": {
      "type": [
        "integer",
        "null"
      ],
      "description": "DAGI id for opstillingskredsen",
      "format": "int32"
    },
    "Kommune": {
      "type": "string",
      "description": "Navn på kommunen"
    },
    "Kommunekode": {
      "type": "integer",
      "description": "Kode på kommunen",
      "format": "int32"
    },
    "AfstemningsområdeNummer": {
      "type": "integer",
      "description": "Nummeret på afstemningsområdet",
      "format": "int32"
    },
    "AfstemningsområdeDagiId": {
      "type": "integer",
      "description": "Afstemningsområde Id i DAGI",
      "format": "int32"
    },
    "Afstemningsområde": {
      "type": "string",
      "description": "Navn på valgområde"
    },
    "UgyldigeFremmødteStemmerÅrsager": {
      "type": "array",
      "description": "Ugyldige fremmødte stemme årsager.",
      "items": {
        "$ref": "#/definitions/InvalidVoteReasonDto"
      }
    },
    "UgyldigeBrevstemmerÅrsager": {
      "type": "array",
      "description": "Ugyldige brevstemmer årsager.",
      "items": {
        "$ref": "#/definitions/InvalidVoteReasonDto"
      }
    },
    "Resultatart": {
      "description": "{Streng af 3 forskellige typer: ['IngenResultater - Resultaterne indeholder kun information om stemmeberettigede vælgere', 'ForeløbigOptælling -  Resultaterne er fra den foreløbige optælling', 'Fintælling - Resultaterne er fra fintælling' ]",
      "oneOf": [
        {
          "$ref": "#/definitions/Resultatart"
        }
      ]
    },
    "AfgivneStemmer": {
      "type": "integer",
      "description": "Summen af gyldige, ugyldige og blanke stemmer",
      "format": "int32"
    },
    "GyldigeStemmer": {
      "type": "integer",
      "description": "Summen af stemmer på alle partier",
      "format": "int32"
    },
    "UgyldigeStemmerUdoverBlanke": {
      "type": "integer",
      "description": "Summen af ugyldige stemmer udover blanke",
      "format": "int32"
    },
    "BlankeUgyldigeFremmødteStemmer": {
      "type": "integer",
      "description": "Summen af blanke fremmødte stemmer",
      "format": "int32"
    },
    "BlankeUgyldigeBrevstemmer": {
      "type": "integer",
      "description": "Summen af blanke brevstemmer",
      "format": "int32"
    },
    "AfgivneStemmerDifferenceFraForrigeValg": {
      "type": [
        "integer",
        "null"
      ],
      "description": "Differencen af afgivne stemmer for det forrige valg",
      "format": "int32"
    },
    "GyldigeStemmerDifferenceFraForrigeValg": {
      "type": [
        "integer",
        "null"
      ],
      "description": "Differencen af gyldige stemmer for det forrige valg",
      "format": "int32"
    },
    "UgyldigeStemmerDifferenceFraForrigeValg": {
      "type": [
        "integer",
        "null"
      ],
      "description": "Differencen af ugyldige stemmer for det forrige valg",
      "format": "int32"
    },
    "BlankeStemmerDifferenceFraForrigeValg": {
      "type": [
        "integer",
        "null"
      ],
      "description": "Differencen af blanke stemmer for det forrige valg",
      "format": "int32"
    },
    "AntalStemmeberettigedeVælgereDifferenceFraForrigeValg": {
      "type": [
        "integer",
        "null"
      ],
      "description": "Differencen af antallet af stemmeberettigede vælgere fra forrige valg",
      "format": "int32"
    },
    "AntalStemmeberettigedeVælgere": {
      "type": "integer",
      "description": "Antallet af stemmeberettigede vælgere",
      "format": "int32"
    },
    "IndenforParti": {
      "type": "array",
      "description": "Indeholder en liste af IndenforParti objekter.",
      "items": {
        "$ref": "#/definitions/Parti"
      }
    },
    "UdenforParti": {
      "type": "array",
      "description": "Indeholder en liste af Kandidat objekter.",
      "items": {
        "$ref": "#/definitions/Kandidat"
      }
    }
  },
  "definitions": {
    "Valgart": {
      "type": "string",
      "enum": [
        "Europa-Parlamentsvalg",
        "Folketingsvalg",
        "Regionsrådsvalg",
        "Kommunalvalg",
        "Folkeafstemning"
      ]
    },
    "InvalidVoteReasonDto": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "Id",
        "Navn",
        "Paragraf",
        "Antal"
      ],
      "properties": {
        "Id": {
          "type": "integer",
          "description": "Identifikationsnummer på ugyldighedsårsagen",
          "format": "int32"
        },
        "Navn": {
          "type": "string",
          "description": "Navnet på ugyldighedsårsagen"
        },
        "Paragraf": {
          "type": [
            "null",
            "string"
          ],
          "description": "Paragrafnumre som ugyldighedsårsagen omhandler"
        },
        "Antal": {
          "type": "integer",
          "description": "Antal ugyldige stemmer med årsagen",
          "format": "int32"
        }
      }
    },
    "Resultatart": {
      "type": "string",
      "enum": [
        "ForeløbigOptælling",
        "Fintælling",
        "IngenResultater"
      ]
    },
    "Parti": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "PartiId",
        "PartiNavn",
        "Bogstavbetegnelse",
        "Stemmer",
        "Partistemmer",
        "StemmerDifferenceFraForrigeValg",
        "Kandidater"
      ],
      "properties": {
        "PartiId": {
          "type": "string",
          "description": "Id'et på partiet",
          "format": "guid"
        },
        "PartiNavn": {
          "type": "string",
          "description": "Navn på partiet registreret på partimeddelelsen"
        },
        "Bogstavbetegnelse": {
          "type": "string",
          "description": "Partibogstav registreret på partimeddelelsen"
        },
        "Stemmer": {
          "type": "integer",
          "description": "Totalen udregnet fra fremmødte stemmer og brevstemmer",
          "format": "int32"
        },
        "Partistemmer": {
          "type": [
            "integer",
            "null"
          ],
          "description": "Antallet af stemmer specifikt på partiet",
          "format": "int32"
        },
        "StemmerDifferenceFraForrigeValg": {
          "type": [
            "integer",
            "null"
          ],
          "description": "Description",
          "format": "int32"
        },
        "Kandidater": {
          "type": [
            "array",
            "null"
          ],
          "description": "Indeholder en liste af Kandidat objekter.",
          "items": {
            "$ref": "#/definitions/Kandidat"
          }
        }
      }
    },
    "Kandidat": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "Id",
        "Stemmeseddelnavn",
        "Stemmer"
      ],
      "properties": {
        "Id": {
          "type": "string",
          "description": "Identifikationsnummer på kandidaten",
          "format": "guid"
        },
        "Stemmeseddelnavn": {
          "type": [
            "null",
            "string"
          ],
          "description": "Stemmeseddelnavnet på kandidaten"
        },
        "Stemmer": {
          "type": "integer",
          "description": "Totalen udregnet fra fremmødte stemmer og brevstemmer",
          "format": "int32"
        }
      }
    }
  }
}

=== deterherligt/valg-data/folketingsvalg-135-24-03-2026/valgresultater/valgresultater-Folketingsvalg-Haderslev_Kommune-Aastrup-240320262026.json
{"IndenforParti":[{"PartiId":"914ae6fd-98a6-4ed6-afd1-60ab809678ed","PartiNavn":"Venstre, Danmarks Liberale Parti","Bogstavbetegnelse":"V","Stemmer":169,"Partistemmer":null,"StemmerDifferenceFraForrigeValg":null,"Kandidater":null},{"PartiId":"1df39501-e08d-42e9-9804-eccf7b1f564a","PartiNavn":"Dansk Folkeparti","Bogstavbetegnelse":"O","Stemmer":136,"Partistemmer":null,"StemmerDifferenceFraForrigeValg":null,"Kandidater":null},{"PartiId":"30375f1d-ff52-4b0d-9964-7147844cd5e7","PartiNavn":"Moderaterne","Bogstavbetegnelse":"M","Stemmer":86,"Partistemmer":null,"StemmerDifferenceFraForrigeValg":null,"Kandidater":null},{"PartiId":"8bb64864-5728-41db-af00-6234795cf340","PartiNavn":"Enhedslisten - De Rød-Grønne","Bogstavbetegnelse":"Ø","Stemmer":41,"Partistemmer":null,"StemmerDifferenceFraForrigeValg":null,"Kandidater":null},{"PartiId":"c01e1c81-e8eb-4f3d-ac55-de9279740a0e","PartiNavn":"Alternativet","Bogstavbetegnelse":"Å","Stemmer":16,"Partistemmer":null,"StemmerDifferenceFraForrigeValg":null,"Kandidater":null},{"PartiId":"fae32292-ff8f-4f27-8218-a9874603e759","PartiNavn":"SF - Socialistisk Folkeparti","Bogstavbetegnelse":"F","Stemmer":111,"Partistemmer":null,"StemmerDifferenceFraForrigeValg":null,"Kandidater":null},{"PartiId":"93a1aa01-2897-474b-8604-a1326c9b3948","PartiNavn":"Radikale Venstre","Bogstavbetegnelse":"B","Stemmer":47,"Partistemmer":null,"StemmerDifferenceFraForrigeValg":null,"Kandidater":null},{"PartiId":"2e08413e-1c5b-4029-8bce-eac0ebff6527","PartiNavn":"Det Konservative Folkeparti","Bogstavbetegnelse":"C","Stemmer":84,"Partistemmer":null,"StemmerDifferenceFraForrigeValg":null,"Kandidater":null},{"PartiId":"2f487db9-0663-429f-a4ec-081ae701723d","PartiNavn":"Socialdemokratiet","Bogstavbetegnelse":"A","Stemmer":322,"Partistemmer":null,"StemmerDifferenceFraForrigeValg":null,"Kandidater":null},{"PartiId":"4d676beb-025b-4d42-ac5d-533d5130a6f3","PartiNavn":"Liberal Alliance","Bogstavbetegnelse":"I","Stemmer":74,"Partistemmer":null,"StemmerDifferenceFraForrigeValg":null,"Kandidater":null},{"PartiId":"89ee100e-d4d6-43b5-83c5-edd5dd02c1fd","PartiNavn":"Borgernes Parti - Lars Boje Mathiesen","Bogstavbetegnelse":"H","Stemmer":28,"Partistemmer":null,"StemmerDifferenceFraForrigeValg":null,"Kandidater":null},{"PartiId":"ffacb8b3-7f7b-4158-a1ee-c0be84a344c6","PartiNavn":"Danmarksdemokraterne - Inger Støjberg","Bogstavbetegnelse":"Æ","Stemmer":66,"Partistemmer":null,"StemmerDifferenceFraForrigeValg":null,"Kandidater":null}],"UdenforParti":[],"Valgdag":"24-03-2026","Valgart":"Folketingsvalg","FrigivelsesTidspunktUTC":"24-03-2026 20:26:33","Storkreds":"Sydjylland","Storkredsnummer":7,"Opstillingskreds":"Haderslev","OpstillingskredsDagiId":403617,"Kommune":"Haderslev","Kommunekode":510,"AfstemningsområdeNummer":6,"AfstemningsområdeDagiId":709256,"Afstemningsområde":"Aastrup","UgyldigeFremmødteStemmerÅrsager":[{"Id":1,"Navn":"Blanke","Paragraf":"4","Antal":15},{"Id":14,"Navn":"AfmærketMedForskelligeFarverOgAndet","Paragraf":"17","Antal":0},{"Id":8,"Navn":"OverstregetUdvisketEllerIkkeFuldtKryds","Paragraf":"11","Antal":0},{"Id":3,"Navn":"HeltEllerDelvistOverstreget","Paragraf":"6","Antal":0},{"Id":10,"Navn":"StemmeseddelIkkeFraAfstemningssted","Paragraf":"13","Antal":0},{"Id":13,"Navn":"StemmeseddelMedTegningPåskrift","Paragraf":"16","Antal":0},{"Id":11,"Navn":"AndetMærkeEndKrydsForudenKryds","Paragraf":"14","Antal":0},{"Id":5,"Navn":"KrydsIflerePartifelter","Paragraf":"8","Antal":0},{"Id":2,"Navn":"AndetMærkeEndKryds","Paragraf":"5","Antal":0},{"Id":4,"Navn":"KrydsUdenForPartifelterne","Paragraf":"7","Antal":0},{"Id":7,"Navn":"KrydsUdForUdenForPartierne","Paragraf":"10","Antal":0},{"Id":6,"Navn":"KrydsRækkerIndIflerePartifelter","Paragraf":"9","Antal":0},{"Id":9,"Navn":"AndreGrunde","Paragraf":"12","Antal":0},{"Id":12,"Navn":"AnførtFlereEndTreKryds","Paragraf":"15","Antal":0}],"UgyldigeBrevstemmerÅrsager":[{"Id":21,"Navn":"Blanke","Paragraf":"19","Antal":2},{"Id":32,"Navn":"UdfyldtPåBagsidenEllerAndet","Paragraf":"31","Antal":0},{"Id":31,"Navn":"StemmeseddelMedTegningPåskrift","Paragraf":"30","Antal":0},{"Id":27,"Navn":"AndreGrunde","Paragraf":"26","Antal":0},{"Id":28,"Navn":"AndetEllerMereEndEnStemmeseddel","Paragraf":"27","Antal":0},{"Id":29,"Navn":"StemmeseddelIkkeFraMinisteren","Paragraf":"28","Antal":0},{"Id":26,"Navn":"ModstridBogstavPartiNavn","Paragraf":"24,25","Antal":0},{"Id":30,"Navn":"KonvolutMedPåskrift","Paragraf":"29","Antal":0},{"Id":24,"Navn":"KunUofficelBogstavPåFlereBogstaver","Paragraf":"22","Antal":0},{"Id":23,"Navn":"KunUofficelBogstavPåEtBogstav","Paragraf":"21","Antal":0},{"Id":25,"Navn":"KunKryds","Paragraf":"23","Antal":0},{"Id":22,"Navn":"KunNavnUofficielBogstav","Paragraf":"20","Antal":0}],"Resultatart":"ForeløbigOptælling","AfgivneStemmer":1197,"GyldigeStemmer":1180,"UgyldigeStemmerUdoverBlanke":0,"BlankeUgyldigeFremmødteStemmer":15,"BlankeUgyldigeBrevstemmer":2,"AfgivneStemmerDifferenceFraForrigeValg":null,"GyldigeStemmerDifferenceFraForrigeValg":null,"UgyldigeStemmerDifferenceFraForrigeValg":null,"BlankeStemmerDifferenceFraForrigeValg":null,"AntalStemmeberettigedeVælgereDifferenceFraForrigeValg":null,"AntalStemmeberettigedeVælgere":1328}

=== deterherligt/valg-data/folketingsvalg-135-24-03-2026/valgresultater/valgresultater-Folketingsvalg-Aabenraa_Kommune-Hellevad-240320261936.json
{"IndenforParti":[{"PartiId":"93a1aa01-2897-474b-8604-a1326c9b3948","PartiNavn":"Radikale Venstre","Bogstavbetegnelse":"B","Stemmer":4,"Partistemmer":null,"StemmerDifferenceFraForrigeValg":null,"Kandidater":null},{"PartiId":"ffacb8b3-7f7b-4158-a1ee-c0be84a344c6","PartiNavn":"Danmarksdemokraterne - Inger Støjberg","Bogstavbetegnelse":"Æ","Stemmer":82,"Partistemmer":null,"StemmerDifferenceFraForrigeValg":null,"Kandidater":null},{"PartiId":"2f487db9-0663-429f-a4ec-081ae701723d","PartiNavn":"Socialdemokratiet","Bogstavbetegnelse":"A","Stemmer":83,"Partistemmer":null,"StemmerDifferenceFraForrigeValg":null,"Kandidater":null},{"PartiId":"914ae6fd-98a6-4ed6-afd1-60ab809678ed","PartiNavn":"Venstre, Danmarks Liberale Parti","Bogstavbetegnelse":"V","Stemmer":124,"Partistemmer":null,"StemmerDifferenceFraForrigeValg":null,"Kandidater":null},{"PartiId":"2e08413e-1c5b-4029-8bce-eac0ebff6527","PartiNavn":"Det Konservative Folkeparti","Bogstavbetegnelse":"C","Stemmer":12,"Partistemmer":null,"StemmerDifferenceFraForrigeValg":null,"Kandidater":null},{"PartiId":"4d676beb-025b-4d42-ac5d-533d5130a6f3","PartiNavn":"Liberal Alliance","Bogstavbetegnelse":"I","Stemmer":69,"Partistemmer":null,"StemmerDifferenceFraForrigeValg":null,"Kandidater":null},{"PartiId":"fae32292-ff8f-4f27-8218-a9874603e759","PartiNavn":"SF - Socialistisk Folkeparti","Bogstavbetegnelse":"F","Stemmer":22,"Partistemmer":null,"StemmerDifferenceFraForrigeValg":null,"Kandidater":null},{"PartiId":"89ee100e-d4d6-43b5-83c5-edd5dd02c1fd","PartiNavn":"Borgernes Parti - Lars Boje Mathiesen","Bogstavbetegnelse":"H","Stemmer":28,"Partistemmer":null,"StemmerDifferenceFraForrigeValg":null,"Kandidater":null},{"PartiId":"1df39501-e08d-42e9-9804-eccf7b1f564a","PartiNavn":"Dansk Folkeparti","Bogstavbetegnelse":"O","Stemmer":63,"Partistemmer":null,"StemmerDifferenceFraForrigeValg":null,"Kandidater":null},{"PartiId":"30375f1d-ff52-4b0d-9964-7147844cd5e7","PartiNavn":"Moderaterne","Bogstavbetegnelse":"M","Stemmer":25,"Partistemmer":null,"StemmerDifferenceFraForrigeValg":null,"Kandidater":null},{"PartiId":"8bb64864-5728-41db-af00-6234795cf340","PartiNavn":"Enhedslisten - De Rød-Grønne","Bogstavbetegnelse":"Ø","Stemmer":3,"Partistemmer":null,"StemmerDifferenceFraForrigeValg":null,"Kandidater":null},{"PartiId":"c01e1c81-e8eb-4f3d-ac55-de9279740a0e","PartiNavn":"Alternativet","Bogstavbetegnelse":"Å","Stemmer":3,"Partistemmer":null,"StemmerDifferenceFraForrigeValg":null,"Kandidater":null}],"UdenforParti":[],"Valgdag":"24-03-2026","Valgart":"Folketingsvalg","FrigivelsesTidspunktUTC":"24-03-2026 19:36:16","Storkreds":"Sydjylland","Storkredsnummer":7,"Opstillingskreds":"Aabenraa","OpstillingskredsDagiId":403621,"Kommune":"Aabenraa","Kommunekode":580,"AfstemningsområdeNummer":2,"AfstemningsområdeDagiId":703772,"Afstemningsområde":"Hellevad","UgyldigeFremmødteStemmerÅrsager":[{"Id":1,"Navn":"Blanke","Paragraf":"4","Antal":5}],"UgyldigeBrevstemmerÅrsager":[{"Id":21,"Navn":"Blanke","Paragraf":"19","Antal":0}],"Resultatart":"ForeløbigOptælling","AfgivneStemmer":524,"GyldigeStemmer":518,"UgyldigeStemmerUdoverBlanke":1,"BlankeUgyldigeFremmødteStemmer":5,"BlankeUgyldigeBrevstemmer":0,"AfgivneStemmerDifferenceFraForrigeValg":null,"GyldigeStemmerDifferenceFraForrigeValg":null,"UgyldigeStemmerDifferenceFraForrigeValg":null,"BlankeStemmerDifferenceFraForrigeValg":null,"AntalStemmeberettigedeVælgereDifferenceFraForrigeValg":null,"AntalStemmeberettigedeVælgere":627}
