=== deterherligt/valg-data/folketingsvalg-135-24-03-2026/Snitfladebeskrivelser/Partistemmefordeling/Partistemmefordeling.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Partistemmefordeling",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "Valgart",
    "Valgdag",
    "FrigivelsesTidspunktUTC",
    "Storkreds",
    "Storkredsnummer",
    "Opstillingskreds",
    "OpstillingskredsDagiId",
    "IndenforParti"
  ],
  "properties": {
    "Valgart": {
      "description": "Navn pċ valget fx.: Folketingsvalg.",
      "oneOf": [
        {
          "$ref": "#/definitions/ExportIndividualElectionDiscriminator"
        }
      ]
    },
    "Valgdag": {
      "type": "string",
      "description": "Dato for valget",
      "format": "date",
      "pattern": "^(0[1-9]|[12][0-9]|3[01])-(0[1-9]|1[0-2])-(\\d{4})$"
    },
    "FrigivelsesTidspunktUTC": {
      "type": "string",
      "description": "UTC DateTime for filens oprettelse.",
      "format": "date-time",
      "pattern": "^(0[1-9]|[12][0-9]|3[01])-(0[1-9]|1[0-2])-(\\d{4}) (0[0-9]|1[0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9])$"
    },
    "Storkreds": {
      "type": [
        "null",
        "string"
      ],
      "description": "Navn pċ storkredsen."
    },
    "Storkredsnummer": {
      "type": [
        "integer",
        "null"
      ],
      "description": "Storkredsnummer for storkredsen.",
      "format": "int32"
    },
    "Opstillingskreds": {
      "type": [
        "null",
        "string"
      ],
      "description": "Navn pċ opstillingskredsen"
    },
    "OpstillingskredsDagiId": {
      "type": [
        "null",
        "string"
      ],
      "description": "DAGI id for opstillingskredsen"
    },
    "IndenforParti": {
      "type": "array",
      "description": "Indeholder en liste af Parti objekter.",
      "items": {
        "$ref": "#/definitions/Parti"
      }
    }
  },
  "definitions": {
    "ExportIndividualElectionDiscriminator": {
      "type": "string",
      "description": "",
      "x-enumNames": [
        "EuropeanParliamentElection",
        "GeneralElection",
        "RegionalElection",
        "MunicipalElection",
        "Referendum"
      ],
      "enum": [
        "Europa-Parlamentsvalg",
        "Folketingsvalg",
        "Regionsrċdsvalg",
        "Kommunalvalg",
        "Folkeafstemning"
      ]
    },
    "Parti": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "PartiId",
        "PartiNavn",
        "Bogstavbetegnelse",
        "Opstillingsform",
        "PersonligeStemmer",
        "Stemmer",
        "Kandidater"
      ],
      "properties": {
        "PartiId": {
          "type": "string",
          "description": "Id'et pċ partiet",
          "format": "guid"
        },
        "PartiNavn": {
          "type": "string",
          "description": "Navn pċ partiet registreret pċ partimeddelelsen"
        },
        "Bogstavbetegnelse": {
          "type": "string",
          "description": "Partibogstav registreret pċ partimeddelelsen"
        },
        "Opstillingsform": {
          "type": [
            "null",
            "string"
          ],
          "description": "Vĉrdien er en af fĝlgende: Partiliste, Sideordnet, Prioriteret sideordnet eller Kredsvis."
        },
        "PersonligeStemmer": {
          "type": "boolean",
          "description": "Viser om partiet bruger personlige stemmer"
        },
        "Stemmer": {
          "type": "integer",
          "description": "Partistemmer, der skal fordeles ud til kandidaterne",
          "format": "int32"
        },
        "Kandidater": {
          "type": "array",
          "description": "Indeholder en liste af Kandidat objekter.",
          "items": {
            "$ref": "#/definitions/Kandidat"
          }
        }
      }
    },
    "Kandidat": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "Id",
        "Stemmeseddelnavn",
        "PersonligeStemmer",
        "TildeltePartistemmer"
      ],
      "properties": {
        "Id": {
          "type": "string",
          "description": "Id'et pċ kandidaten",
          "format": "guid"
        },
        "Stemmeseddelnavn": {
          "type": [
            "null",
            "string"
          ],
          "description": "Stemmeseddelnavnet pċ kandidaten"
        },
        "PersonligeStemmer": {
          "type": "integer",
          "description": "Kandidatens personlige stemmer",
          "format": "int32"
        },
        "TildeltePartistemmer": {
          "type": "integer",
          "description": "Partistemmer som er blevet tildelt til denne kandidat",
          "format": "int32"
        }
      }
    }
  }
}

=== deterherligt/valg-data/folketingsvalg-135-24-03-2026/partistemmefordeling/partistemmefordeling-Folketingsvalg-Sjælland-Holbæk-250320261259.json
{"Valgart":"Folketingsvalg","Valgdag":"24-03-2026","FrigivelsesTidspunktUTC":"25-03-2026 12:59:48","Storkreds":"Sjælland","Storkredsnummer":5,"Opstillingskreds":"Holbæk","OpstillingskredsDagiId":"403628","IndenforParti":[{"PartiId":"1df39501-e08d-42e9-9804-eccf7b1f564a","PartiNavn":"Dansk Folkeparti","Bogstavbetegnelse":"O","Opstillingsform":"Prioriteret sideordnet","PersonligeStemmer":true,"Stemmer":0,"Kandidater":[{"Id":"41080326-1d01-4340-85b2-dc55cc2fa04a","Stemmeseddelnavn":"Tanja Glückstadt","PersonligeStemmer":16,"TildeltePartistemmer":0},{"Id":"cd0b769b-57ff-434a-953a-80f53356aa35","Stemmeseddelnavn":"Anders Bork","PersonligeStemmer":11,"TildeltePartistemmer":0},{"Id":"844ab4ef-efdb-4daf-9b39-0571bc981968","Stemmeseddelnavn":"Julie Jacobsen","PersonligeStemmer":87,"TildeltePartistemmer":0},{"Id":"f5da0210-3983-4336-88ce-56546c7208f5","Stemmeseddelnavn":"Henrik Brodersen","PersonligeStemmer":10,"TildeltePartistemmer":0},{"Id":"ade9db3c-aa7e-46ef-82c1-191184206e50","Stemmeseddelnavn":"Jacob Bentsen","PersonligeStemmer":8,"TildeltePartistemmer":0},{"Id":"7852d970-e5c2-4caa-8f2d-395c39c6cf0d","Stemmeseddelnavn":"Jan Herskov","PersonligeStemmer":33,"TildeltePartistemmer":0},{"Id":"49903c27-13ef-4f92-95e3-0c986d369796","Stemmeseddelnavn":"Simon Hampe","PersonligeStemmer":5,"TildeltePartistemmer":0},{"Id":"8a1b42fa-0863-4dfd-9405-f576309825b8","Stemmeseddelnavn":"Morten Messerschmidt","PersonligeStemmer":4135,"TildeltePartistemmer":0},{"Id":"a4c7338e-93de-4908-8ea1-4bdeffb4be9f","Stemmeseddelnavn":"Søren Lund Hansen","PersonligeStemmer":28,"TildeltePartistemmer":0},{"Id":"0c8532a7-5cdb-404f-bed4-a062b5f43917","Stemmeseddelnavn":"Michael Pihl","PersonligeStemmer":3,"TildeltePartistemmer":0},{"Id":"09fbc376-a347-449b-a721-fe2e64a82bd7","Stemmeseddelnavn":"Malte Larsen","PersonligeStemmer":70,"TildeltePartistemmer":0}]},{"PartiId":"2e08413e-1c5b-4029-8bce-eac0ebff6527","PartiNavn":"Det Konservative Folkeparti","Bogstavbetegnelse":"C","Opstillingsform":"Prioriteret sideordnet","PersonligeStemmer":true,"Stemmer":0,"Kandidater":[{"Id":"77931313-1a4e-49b7-b41e-aa2b68878553","Stemmeseddelnavn":"Ida Dyhr","PersonligeStemmer":106,"TildeltePartistemmer":0},{"Id":"af4a0617-f6b3-415f-9e0d-c971ba0cab04","Stemmeseddelnavn":"Vilhelm Møller","PersonligeStemmer":38,"TildeltePartistemmer":0},{"Id":"eae11395-1cc3-4d63-b797-ee7453f32f4d","Stemmeseddelnavn":"Victoria Helene Olsen","PersonligeStemmer":54,"TildeltePartistemmer":0},{"Id":"856e1c2d-7509-4b85-96af-b01de0b6d523","Stemmeseddelnavn":"Jane Christensen","PersonligeStemmer":27,"TildeltePartistemmer":0},{"Id":"5fb8791e-954b-44e1-b8cc-31cd816211d3","Stemmeseddelnavn":"Marcus Knuth","PersonligeStemmer":232,"TildeltePartistemmer":0},{"Id":"abffa718-b6ee-4c0b-b62a-a70630e7eb2e","Stemmeseddelnavn":"Ditte Keidser","PersonligeStemmer":106,"TildeltePartistemmer":0},{"Id":"f59ad3ab-6fb2-4963-a673-f575dfc41c97","Stemmeseddelnavn":"Silas Ipsen","PersonligeStemmer":30,"TildeltePartistemmer":0},{"Id":"75dc08ce-8e1d-4701-89c8-af9d5dd34c97","Stemmeseddelnavn":"Mads Ramstedt","PersonligeStemmer":6,"TildeltePartistemmer":0},{"Id":"6d37be75-7bfe-485c-ae93-6515445e6261","Stemmeseddelnavn":"Jacob Stryhn","PersonligeStemmer":32,"TildeltePartistemmer":0},{"Id":"843653d5-fffd-4e6e-a0e7-9ca4e9684fbf","Stemmeseddelnavn":"Rune Kristensen","PersonligeStemmer":29,"TildeltePartistemmer":0},{"Id":"9d607511-53c2-4cc1-b92f-6d51032bb6e9","Stemmeseddelnavn":"Barbara Engelstoft","PersonligeStemmer":32,"TildeltePartistemmer":0},{"Id":"a0162cb4-6f33-47bb-afbc-bf6c06b0e6b0","Stemmeseddelnavn":"Henrik Jacobsen","PersonligeStemmer":6,"TildeltePartistemmer":0}]},{"PartiId":"2f487db9-0663-429f-a4ec-081ae701723d","PartiNavn":"Socialdemokratiet","Bogstavbetegnelse":"A","Opstillingsform":"Prioriteret sideordnet","PersonligeStemmer":true,"Stemmer":0,"Kandidater":[{"Id":"a238bb65-5e77-421f-b409-ab0f2fd6a333","Stemmeseddelnavn":"Frederik Vad","PersonligeStemmer":390,"TildeltePartistemmer":0},{"Id":"cc43cca2-2607-4084-b88d-56ba802746d2","Stemmeseddelnavn":"Carl Emil Lind","PersonligeStemmer":65,"TildeltePartistemmer":0},{"Id":"ee2f3b28-7fe1-4e46-91ec-61486c92e630","Stemmeseddelnavn":"Kanishka Dastageer","PersonligeStemmer":41,"TildeltePartistemmer":0},{"Id":"5e29d40d-7127-40b7-9750-651ffcc668be","Stemmeseddelnavn":"Tanja Larsson","PersonligeStemmer":57,"TildeltePartistemmer":0},{"Id":"36940374-2891-4bc8-ad7d-75102339bef4","Stemmeseddelnavn":"Julie Kølskov","PersonligeStemmer":49,"TildeltePartistemmer":0},{"Id":"720e060b-9314-462f-9418-270c6228a6a5","Stemmeseddelnavn":"Rasmus Horn Langhoff","PersonligeStemmer":94,"TildeltePartistemmer":0},{"Id":"10265942-527f-497f-a4e5-0e42e53548de","Stemmeseddelnavn":"Trine Birk Andersen","PersonligeStemmer":2127,"TildeltePartistemmer":0},{"Id":"48099ab8-eaa7-450e-b4ab-4427d8b9a0a8","Stemmeseddelnavn":"Kasper Roug","PersonligeStemmer":8,"TildeltePartistemmer":0},{"Id":"bfa3f7e1-e5d2-4879-a7b0-bca6aec74b37","Stemmeseddelnavn":"Magnus Heunicke","PersonligeStemmer":516,"TildeltePartistemmer":0},{"Id":"ad8f41ea-4b31-4d1a-9165-062ed7b1e8bf","Stemmeseddelnavn":"Valdemar Alban","PersonligeStemmer":20,"TildeltePartistemmer":0},{"Id":"59324198-5cb2-45d0-8071-9985a9203de3","Stemmeseddelnavn":"Filiz Sarah Thunø","PersonligeStemmer":16,"TildeltePartistemmer":0},{"Id":"575f0bce-8687-4b23-9adc-7e92c59fdf92","Stemmeseddelnavn":"Kaare Dybvad Bek","PersonligeStemmer":1656,"TildeltePartistemmer":0}]},{"PartiId":"30375f1d-ff52-4b0d-9964-7147844cd5e7","PartiNavn":"Moderaterne","Bogstavbetegnelse":"M","Opstillingsform":"Prioriteret sideordnet","PersonligeStemmer":true,"Stemmer":0,"Kandidater":[{"Id":"a510a8a3-294c-47cc-b412-32ab33906c9e","Stemmeseddelnavn":"Jan Carlsen","PersonligeStemmer":8,"TildeltePartistemmer":0},{"Id":"4256efd1-c1b1-4d0a-ad57-8aec46ca76ad","Stemmeseddelnavn":"Mia Linda Møller","PersonligeStemmer":15,"TildeltePartistemmer":0},{"Id":"23d317fa-538b-49dd-bfa4-8912decb0add","Stemmeseddelnavn":"Mogens Haugaard","PersonligeStemmer":12,"TildeltePartistemmer":0},{"Id":"1fd93cd3-e6c9-4c94-9166-ac30eb075ee1","Stemmeseddelnavn":"Lars Løkke Rasmussen","PersonligeStemmer":3096,"TildeltePartistemmer":0},{"Id":"d7c1739f-c184-4fc2-9102-0e0a8fdb7646","Stemmeseddelnavn":"Frida Qvist Kristensen","PersonligeStemmer":15,"TildeltePartistemmer":0},{"Id":"70ba920a-da31-4501-b67c-a5d30353e595","Stemmeseddelnavn":"Brian Perri","PersonligeStemmer":117,"TildeltePartistemmer":0},{"Id":"dda08e60-a6f5-4606-a10f-71b8a29af055","Stemmeseddelnavn":"Charlotte Bagge","PersonligeStemmer":51,"TildeltePartistemmer":0},{"Id":"e2779dae-560c-4eb3-a808-6146e785ec1c","Stemmeseddelnavn":"Kasper Nygaard","PersonligeStemmer":14,"TildeltePartistemmer":0}]},{"PartiId":"4d676beb-025b-4d42-ac5d-533d5130a6f3","PartiNavn":"Liberal Alliance","Bogstavbetegnelse":"I","Opstillingsform":"Prioriteret sideordnet","PersonligeStemmer":true,"Stemmer":0,"Kandidater":[{"Id":"45b3d484-5174-4068-9e76-90da266003ee","Stemmeseddelnavn":"Elva Bille Klem","PersonligeStemmer":4,"TildeltePartistemmer":0},{"Id":"f9ea552f-a527-44fc-a3fa-1dc960748d49","Stemmeseddelnavn":"Joachim Riis","PersonligeStemmer":92,"TildeltePartistemmer":0},{"Id":"9dfd02fa-02ca-4511-87c6-50291029f6d7","Stemmeseddelnavn":"Susan H. Møller","PersonligeStemmer":3,"TildeltePartistemmer":0},{"Id":"73057ed2-fa10-4c61-a328-58144c37597b","Stemmeseddelnavn":"Kasper Schneider","PersonligeStemmer":7,"TildeltePartistemmer":0},{"Id":"b29c755e-e03e-47e4-b208-9c8256c85a52","Stemmeseddelnavn":"Sandra Skalvig","PersonligeStemmer":10,"TildeltePartistemmer":0},{"Id":"910fc206-2fc6-4526-9c9b-8a6bbfd0bfc7","Stemmeseddelnavn":"Frederik Max Krag","PersonligeStemmer":1,"TildeltePartistemmer":0},{"Id":"522cdead-8189-49a7-8cae-a528173c8afc","Stemmeseddelnavn":"Martin Mickey Pedersen","PersonligeStemmer":6,"TildeltePartistemmer":0},{"Id":"32d3926d-cc00-4ceb-bd35-8dfb74ab83e9","Stemmeseddelnavn":"Henrik B. Dynesen","PersonligeStemmer":3,"TildeltePartistemmer":0},{"Id":"dfe9c059-09ad-4334-b23c-8e57f1c6aff2","Stemmeseddelnavn":"Nicolai Sandager","PersonligeStemmer":4,"TildeltePartistemmer":0},{"Id":"b029cb7d-0672-4f0c-a8fe-a0ecd1c8053e","Stemmeseddelnavn":"Nikolaj Brink Olsen","PersonligeStemmer":2,"TildeltePartistemmer":0},{"Id":"51910da3-ac3d-49b8-9968-6dcb265db17b","Stemmeseddelnavn":"Julie Memborg","PersonligeStemmer":12,"TildeltePartistemmer":0},{"Id":"0d9627cf-cc3f-44ff-bb1a-89e173c205c0","Stemmeseddelnavn":"Ulrik Lassen","PersonligeStemmer":6,"TildeltePartistemmer":0},{"Id":"1355711b-9ca6-4051-bc8f-b1dfbc956118","Stemmeseddelnavn":"Steffen Friis","PersonligeStemmer":3,"TildeltePartistemmer":0},{"Id":"f20ca956-8869-4963-ad64-834f041b156d","Stemmeseddelnavn":"Brian Prehn","PersonligeStemmer":9,"TildeltePartistemmer":0},{"Id":"ab45a5bb-f9a5-4642-b5f1-e7beaffd1771","Stemmeseddelnavn":"Lars-Christian Brask","PersonligeStemmer":86,"TildeltePartistemmer":0},{"Id":"c284bb31-23f2-480c-a5bc-57488bc1e1b8","Stemmeseddelnavn":"Carsten Abildtrup Ranum","PersonligeStemmer":3,"TildeltePartistemmer":0},{"Id":"2ade7adb-aa2a-433e-8215-350b693843f1","Stemmeseddelnavn":"Mads Brenøe","PersonligeStemmer":27,"TildeltePartistemmer":0},{"Id":"ce22fcb2-bee3-4797-b303-01946261b45e","Stemmeseddelnavn":"Frederik Grünfeld","PersonligeStemmer":212,"TildeltePartistemmer":0},{"Id":"a45ef5ff-312b-4a59-a78e-084a44823acb","Stemmeseddelnavn":"Michael Rask","PersonligeStemmer":9,"TildeltePartistemmer":0},{"Id":"f01c6857-5fc0-40c3-8e54-a3ae1b8e3fa6","Stemmeseddelnavn":"Pernille Vermund","PersonligeStemmer":473,"TildeltePartistemmer":0}]},{"PartiId":"89ee100e-d4d6-43b5-83c5-edd5dd02c1fd","PartiNavn":"Borgernes Parti - Lars Boje Mathiesen","Bogstavbetegnelse":"H","Opstillingsform":"Prioriteret sideordnet","PersonligeStemmer":true,"Stemmer":0,"Kandidater":[{"Id":"c67828c4-11a1-455f-b501-f603d49d0671","Stemmeseddelnavn":"John Bo Hansen","PersonligeStemmer":12,"TildeltePartistemmer":0},{"Id":"03561610-21cc-4e68-b8a9-6cafa410c5b5","Stemmeseddelnavn":"Jacob Harris","PersonligeStemmer":209,"TildeltePartistemmer":0},{"Id":"da7a9a6d-1740-4d07-8c84-e8223fe60806","
