=== deterherligt/valg-data/folketingsvalg-135-24-03-2026/Snitfladebeskrivelser/Valgdeltagelse/Valgdeltagelse.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Valgdeltagelse",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "Valgart",
    "Valgdag",
    "FrigivelsesTidspunktUTC",
    "Kommune",
    "Kommunekode",
    "Afstemningsområde",
    "AfstemningsområdeDagiId",
    "AfstemningsområdeNummer",
    "Valgdeltagelse"
  ],
  "properties": {
    "Valgart": {
      "type": "string",
      "description": "Navn på valget fx.: Folketingsvalg."
    },
    "Valgdag": {
      "type": "string",
      "description": "Dato for valget",
      "format": "date",
      "pattern": "^(0[1-9]|[12][0-9]|3[01])-(0[1-9]|1[0-2])-(\\d{4})$"
    },
    "FrigivelsesTidspunktUTC": {
      "type": "string",
      "description": "UTC DateTime for filens oprettelse.",
      "format": "date-time",
      "pattern": "^(0[1-9]|[12][0-9]|3[01])-(0[1-9]|1[0-2])-(\\d{4}) (0[0-9]|1[0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9])$"
    },
    "Kommune": {
      "type": "string",
      "description": "Navn på kommunen"
    },
    "Kommunekode": {
      "type": "integer",
      "description": "Kode på kommunen",
      "format": "int32"
    },
    "Afstemningsområde": {
      "type": "string",
      "description": "Navn på afstemningsområde"
    },
    "AfstemningsområdeDagiId": {
      "type": "string",
      "description": "Afstemningsområde Id i DAGI"
    },
    "AfstemningsområdeNummer": {
      "type": "integer",
      "description": "Nummeret på afstemningsområdet",
      "format": "int32"
    },
    "Valgdeltagelse": {
      "type": "array",
      "description": "Indeholder en liste af Valgdeltagelse objekter.",
      "items": {
        "$ref": "#/definitions/Valgdeltagelse"
      }
    }
  },
  "definitions": {
    "Valgdeltagelse": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "AntalStemmeberretigedeVælgere",
        "AfgivneStemmer",
        "Tidspunkt"
      ],
      "properties": {
        "AntalStemmeberretigedeVælgere": {
          "type": "integer",
          "description": "Antallet på stemmeberettigede vælgere",
          "format": "int32"
        },
        "AfgivneStemmer": {
          "type": "integer",
          "description": "Antallet af afgivne stemmer",
          "format": "int32"
        },
        "Tidspunkt": {
          "type": "string",
          "description": "Tidspunktet for hvornår denne valgdeltagelse blev registreret på formatet: tt:mm.",
          "format": "time"
        }
      }
    }
  }
}

=== deterherligt/valg-data/folketingsvalg-135-24-03-2026/valgdeltagelse/valgdeltagelse-Folketingsvalg-Slagelse_Kommune-Skælskør_-_Skælskør_Badmintoncenter-240320261507.json
{"Valgart":"Folketingsvalg","Valgdag":"24-03-2026","FrigivelsesTidspunktUTC":"24-03-2026 15:07:00","Kommune":"Slagelse","Kommunekode":330,"Afstemningsområde":"Skælskør - Skælskør Badmintoncenter","AfstemningsområdeDagiId":"720074","AfstemningsområdeNummer":6,"Valgdeltagelse":[{"AntalStemmeberretigedeVælgere":6386,"AfgivneStemmer":2049,"Tidspunkt":"12:00:00"},{"AntalStemmeberretigedeVælgere":6386,"AfgivneStemmer":2708,"Tidspunkt":"14:00:00"},{"AntalStemmeberretigedeVælgere":6386,"AfgivneStemmer":3566,"Tidspunkt":"16:00:00"}]}

=== deterherligt/valg-data/folketingsvalg-135-24-03-2026/valgdeltagelse/valgdeltagelse-Folketingsvalg-Gentofte_Kommune-Rådhuset-240320261303.json
{"Valgart":"Folketingsvalg","Valgdag":"24-03-2026","FrigivelsesTidspunktUTC":"24-03-2026 13:03:54","Kommune":"Gentofte","Kommunekode":157,"Afstemningsområde":"Rådhuset","AfstemningsområdeDagiId":"702884","AfstemningsområdeNummer":3,"Valgdeltagelse":[{"AntalStemmeberretigedeVælgere":5768,"AfgivneStemmer":1238,"Tidspunkt":"08:00:00"},{"AntalStemmeberretigedeVælgere":5768,"AfgivneStemmer":1685,"Tidspunkt":"09:00:00"},{"AntalStemmeberretigedeVælgere":5768,"AfgivneStemmer":1882,"Tidspunkt":"10:00:00"},{"AntalStemmeberretigedeVælgere":5768,"AfgivneStemmer":2105,"Tidspunkt":"11:00:00"},{"AntalStemmeberretigedeVælgere":5768,"AfgivneStemmer":2355,"Tidspunkt":"12:00:00"},{"AntalStemmeberretigedeVælgere":5768,"AfgivneStemmer":2576,"Tidspunkt":"13:00:00"},{"AntalStemmeberretigedeVælgere":5768,"AfgivneStemmer":2789,"Tidspunkt":"14:00:00"}]}

=== deterherligt/valg-data/folketingsvalg-135-24-03-2026/valgdeltagelse/valgdeltagelse-Folketingsvalg-Aarhus_Kommune-Skjoldhøjskolen,_Tilst-240320260809.json
{"Valgart":"Folketingsvalg","Valgdag":"24-03-2026","FrigivelsesTidspunktUTC":"24-03-2026 08:09:17","Kommune":"Aarhus","Kommunekode":751,"Afstemningsområde":"Skjoldhøjskolen, Tilst","AfstemningsområdeDagiId":"710040","AfstemningsområdeNummer":26,"Valgdeltagelse":[{"AntalStemmeberretigedeVælgere":4023,"AfgivneStemmer":471,"Tidspunkt":"09:00:00"}]}

=== deterherligt/valg-data/folketingsvalg-135-24-03-2026/valgdeltagelse/valgdeltagelse-Folketingsvalg-Hørsholm_Kommune-Rungsted-240320261006.json
{"Valgart":"Folketingsvalg","Valgdag":"24-03-2026","FrigivelsesTidspunktUTC":"24-03-2026 10:06:32","Kommune":"Hørsholm","Kommunekode":223,"Afstemningsområde":"Rungsted","AfstemningsområdeDagiId":"707688","AfstemningsområdeNummer":3,"Valgdeltagelse":[{"AntalStemmeberretigedeVælgere":3432,"AfgivneStemmer":547,"Tidspunkt":"08:00:00"},{"AntalStemmeberretigedeVælgere":3432,"AfgivneStemmer":806,"Tidspunkt":"09:00:00"},{"AntalStemmeberretigedeVælgere":3432,"AfgivneStemmer":979,"Tidspunkt":"10:00:00"},{"AntalStemmeberretigedeVælgere":3432,"AfgivneStemmer":1186,"Tidspunkt":"11:00:00"}]}

=== deterherligt/valg-data/folketingsvalg-135-24-03-2026/valgdeltagelse/valgdeltagelse-Folketingsvalg-Jammerbugt_Kommune-Vedsted-240320261127.json
{"Valgart":"Folketingsvalg","Valgdag":"24-03-2026","FrigivelsesTidspunktUTC":"24-03-2026 11:27:56","Kommune":"Jammerbugt","Kommunekode":849,"Afstemningsområde":"Vedsted","AfstemningsområdeDagiId":"711896","AfstemningsområdeNummer":4,"Valgdeltagelse":[{"AntalStemmeberretigedeVælgere":882,"AfgivneStemmer":257,"Tidspunkt":"12:00:00"}]}

=== deterherligt/valg-data/folketingsvalg-135-24-03-2026/valgdeltagelse/valgdeltagelse-Folketingsvalg-Svendborg_Kommune-Egense-240320261400.json
{"Valgart":"Folketingsvalg","Valgdag":"24-03-2026","FrigivelsesTidspunktUTC":"24-03-2026 14:00:17","Kommune":"Svendborg","Kommunekode":479,"Afstemningsområde":"Egense","AfstemningsområdeDagiId":"705328","AfstemningsområdeNummer":7,"Valgdeltagelse":[{"AntalStemmeberretigedeVælgere":2167,"AfgivneStemmer":411,"Tidspunkt":"09:23:00"},{"AntalStemmeberretigedeVælgere":2167,"AfgivneStemmer":694,"Tidspunkt":"11:00:00"},{"AntalStemmeberretigedeVælgere":2167,"AfgivneStemmer":944,"Tidspunkt":"13:00:00"},{"AntalStemmeberretigedeVælgere":2167,"AfgivneStemmer":1144,"Tidspunkt":"15:00:00"}]}

=== deterherligt/valg-data/folketingsvalg-135-24-03-2026/valgdeltagelse/valgdeltagelse-Folketingsvalg-Frederikshavn_Kommune-Skagen-240320261101.json
{"Valgart":"Folketingsvalg","Valgdag":"24-03-2026","FrigivelsesTidspunktUTC":"24-03-2026 11:01:08","Kommune":"Frederikshavn","Kommunekode":813,"Afstemningsområde":"Skagen","AfstemningsområdeDagiId":"705148","AfstemningsområdeNummer":1,"Valgdeltagelse":[{"AntalStemmeberretigedeVælgere":5409,"AfgivneStemmer":653,"Tidspunkt":"09:00:00"},{"AntalStemmeberretigedeVælgere":5409,"AfgivneStemmer":1050,"Tidspunkt":"10:00:00"},{"AntalStemmeberretigedeVælgere":5409,"AfgivneStemmer":1878,"Tidspunkt":"12:00:00"}]}

=== deterherligt/valg-data/folketingsvalg-135-24-03-2026/valgdeltagelse/valgdeltagelse-Folketingsvalg-Horsens_Kommune-Lund-240320261321.json
{"Valgart":"Folketingsvalg","Valgdag":"24-03-2026","FrigivelsesTidspunktUTC":"24-03-2026 13:21:28","Kommune":"Horsens","Kommunekode":615,"Afstemningsområde":"Lund","AfstemningsområdeDagiId":"710912","AfstemningsområdeNummer":9,"Valgdeltagelse":[{"AntalStemmeberretigedeVælgere":3456,"AfgivneStemmer":449,"Tidspunkt":"09:00:00"},{"AntalStemmeberretigedeVælgere":3456,"AfgivneStemmer":609,"Tidspunkt":"10:00:00"},{"AntalStemmeberretigedeVælgere":3456,"AfgivneStemmer":786,"Tidspunkt":"11:00:00"},{"AntalStemmeberretigedeVælgere":3456,"AfgivneStemmer":982,"Tidspunkt":"12:00:00"},{"AntalStemmeberretigedeVælgere":3456,"AfgivneStemmer":1141,"Tidspunkt":"13:00:00"},{"AntalStemmeberretigedeVælgere":3456,"AfgivneStemmer":1288,"Tidspunkt":"14:00:00"}]}
