=== deterherligt/valg-data/folketingsvalg-135-24-03-2026/Snitfladebeskrivelser/Valgdeltagelse/Valgdeltagelse.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Valgdeltagelse",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "Valgart",
    "Valgdag",
    "FrigivelsesTidspunktUTC",
    "Kommune",
    "Kommunekode",
    "Afstemningsområde",
    "AfstemningsområdeDagiId",
    "AfstemningsområdeNummer",
    "Valgdeltagelse"
  ],
  "properties": {
    "Valgart": {
      "type": "string",
      "description": "Navn på valget fx.: Folketingsvalg."
    },
    "Valgdag": {
      "type": "string",
      "description": "Dato for valget",
      "format": "date",
      "pattern": "^(0[1-9]|[12][0-9]|3[01])-(0[1-9]|1[0-2])-(\\d{4})$"
    },
    "FrigivelsesTidspunktUTC": {
      "type": "string",
      "description": "UTC DateTime for filens oprettelse.",
      "format": "date-time",
      "pattern": "^(0[1-9]|[12][0-9]|3[01])-(0[1-9]|1[0-2])-(\\d{4}) (0[0-9]|1[0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9])$"
    },
    "Kommune": {
      "type": "string",
      "description": "Navn på kommunen"
    },
    "Kommunekode": {
      "type": "integer",
      "description": "Kode på kommunen",
      "format": "int32"
    },
    "Afstemningsområde": {
      "type": "string",
      "description": "Navn på afstemningsområde"
    },
    "AfstemningsområdeDagiId": {
      "type": "string",
      "description": "Afstemningsområde Id i DAGI"
    },
    "AfstemningsområdeNummer": {
      "type": "integer",
      "description": "Nummeret på afstemningsområdet",
      "format": "int32"
    },
    "Valgdeltagelse": {
      "type": "array",
      "description": "Indeholder en liste af Valgdeltagelse objekter.",
      "items": {
        "$ref": "#/definitions/Valgdeltagelse"
      }
    }
  },
  "definitions": {
    "Valgdeltagelse": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "AntalStemmeberretigedeVælgere",
        "AfgivneStemmer",
        "Tidspunkt"
      ],
      "properties": {
        "AntalStemmeberretigedeVælgere": {
          "type": "integer",
          "description": "Antallet på stemmeberettigede vælgere",
          "format": "int32"
        },
        "AfgivneStemmer": {
          "type": "integer",
          "description": "Antallet af afgivne stemmer",
          "format": "int32"
        },
        "Tidspunkt": {
          "type": "string",
          "description": "Tidspunktet for hvornår denne valgdeltagelse blev registreret på formatet: tt:mm.",
          "format": "time"
        }
      }
    }
  }
}

=== deterherligt/valg-data/folketingsvalg-135-24-03-2026/valgdeltagelse/valgdeltagelse-Folketingsvalg-Brønderslev_Kommune-Stenum-240320261511.json
{"Valgart":"Folketingsvalg","Valgdag":"24-03-2026","FrigivelsesTidspunktUTC":"24-03-2026 15:11:17","Kommune":"Brønderslev","Kommunekode":810,"Afstemningsområde":"Stenum","AfstemningsområdeDagiId":"702304","AfstemningsområdeNummer":34,"Valgdeltagelse":[{"AntalStemmeberretigedeVælgere":462,"AfgivneStemmer":103,"Tidspunkt":"12:00:00"},{"AntalStemmeberretigedeVælgere":462,"AfgivneStemmer":231,"Tidspunkt":"16:00:00"}]}

=== deterherligt/valg-data/folketingsvalg-135-24-03-2026/valgdeltagelse/valgdeltagelse-Folketingsvalg-Herning_Kommune-Ørnhøj-240320261306.json
{"Valgart":"Folketingsvalg","Valgdag":"24-03-2026","FrigivelsesTidspunktUTC":"24-03-2026 13:06:55","Kommune":"Herning","Kommunekode":657,"Afstemningsområde":"Ørnhøj","AfstemningsområdeDagiId":"705030","AfstemningsområdeNummer":30,"Valgdeltagelse":[{"AntalStemmeberretigedeVælgere":784,"AfgivneStemmer":69,"Tidspunkt":"09:00:00"},{"AntalStemmeberretigedeVælgere":784,"AfgivneStemmer":161,"Tidspunkt":"11:00:00"},{"AntalStemmeberretigedeVælgere":784,"AfgivneStemmer":264,"Tidspunkt":"14:00:00"}]}

=== deterherligt/valg-data/folketingsvalg-135-24-03-2026/valgdeltagelse/valgdeltagelse-Folketingsvalg-Nyborg_Kommune-Skellerup-240320261802.json
{"Valgart":"Folketingsvalg","Valgdag":"24-03-2026","FrigivelsesTidspunktUTC":"24-03-2026 18:02:20","Kommune":"Nyborg","Kommunekode":450,"Afstemningsområde":"Skellerup","AfstemningsområdeDagiId":"703760","AfstemningsområdeNummer":8,"Valgdeltagelse":[{"AntalStemmeberretigedeVælgere":416,"AfgivneStemmer":37,"Tidspunkt":"09:00:00"},{"AntalStemmeberretigedeVælgere":416,"AfgivneStemmer":62,"Tidspunkt":"10:00:00"},{"AntalStemmeberretigedeVælgere":416,"AfgivneStemmer":87,"Tidspunkt":"11:00:00"},{"AntalStemmeberretigedeVælgere":416,"AfgivneStemmer":108,"Tidspunkt":"12:00:00"},{"AntalStemmeberretigedeVælgere":416,"AfgivneStemmer":129,"Tidspunkt":"13:00:00"},{"AntalStemmeberretigedeVælgere":416,"AfgivneStemmer":144,"Tidspunkt":"14:00:00"},{"AntalStemmeberretigedeVælgere":416,"AfgivneStemmer":172,"Tidspunkt":"15:00:00"},{"AntalStemmeberretigedeVælgere":416,"AfgivneStemmer":212,"Tidspunkt":"16:00:00"},{"AntalStemmeberretigedeVælgere":416,"AfgivneStemmer":269,"Tidspunkt":"17:00:00"},{"AntalStemmeberretigedeVælgere":416,"AfgivneStemmer":315,"Tidspunkt":"18:00:00"},{"AntalStemmeberretigedeVælgere":416,"AfgivneStemmer":342,"Tidspunkt":"19:00:00"}]}

=== deterherligt/valg-data/folketingsvalg-135-24-03-2026/valgdeltagelse/valgdeltagelse-Folketingsvalg-Hjørring_Kommune-Hundelev-240320261006.json
{"Valgart":"Folketingsvalg","Valgdag":"24-03-2026","FrigivelsesTidspunktUTC":"24-03-2026 10:06:02","Kommune":"Hjørring","Kommunekode":860,"Afstemningsområde":"Hundelev","AfstemningsområdeDagiId":"710482","AfstemningsområdeNummer":20,"Valgdeltagelse":[{"AntalStemmeberretigedeVælgere":762,"AfgivneStemmer":54,"Tidspunkt":"09:00:00"},{"AntalStemmeberretigedeVælgere":762,"AfgivneStemmer":124,"Tidspunkt":"11:00:00"}]}

=== deterherligt/valg-data/folketingsvalg-135-24-03-2026/valgdeltagelse/valgdeltagelse-Folketingsvalg-Aarhus_Kommune-Samsøgades_Skole,_Aarhus_C-240320261414.json
{"Valgart":"Folketingsvalg","Valgdag":"24-03-2026","FrigivelsesTidspunktUTC":"24-03-2026 14:14:50","Kommune":"Aarhus","Kommunekode":751,"Afstemningsområde":"Samsøgades Skole, Aarhus C","AfstemningsområdeDagiId":"711398","AfstemningsområdeNummer":41,"Valgdeltagelse":[{"AntalStemmeberretigedeVælgere":7076,"AfgivneStemmer":1363,"Tidspunkt":"09:00:00"},{"AntalStemmeberretigedeVælgere":7076,"AfgivneStemmer":2291,"Tidspunkt":"11:30:00"},{"AntalStemmeberretigedeVælgere":7076,"AfgivneStemmer":3690,"Tidspunkt":"15:00:00"}]}

=== deterherligt/valg-data/folketingsvalg-135-24-03-2026/valgdeltagelse/valgdeltagelse-Folketingsvalg-Ballerup_Kommune-Grantoftehallen-240320261004.json
{"Valgart":"Folketingsvalg","Valgdag":"24-03-2026","FrigivelsesTidspunktUTC":"24-03-2026 10:04:32","Kommune":"Ballerup","Kommunekode":151,"Afstemningsområde":"Grantoftehallen","AfstemningsområdeDagiId":"710158","AfstemningsområdeNummer":4,"Valgdeltagelse":[{"AntalStemmeberretigedeVælgere":3421,"AfgivneStemmer":358,"Tidspunkt":"09:00:00"},{"AntalStemmeberretigedeVælgere":3421,"AfgivneStemmer":463,"Tidspunkt":"10:00:00"}]}

=== deterherligt/valg-data/folketingsvalg-135-24-03-2026/valgdeltagelse/valgdeltagelse-Folketingsvalg-Fredensborg_Kommune-Karlebo-240320261501.json
{"Valgart":"Folketingsvalg","Valgdag":"24-03-2026","FrigivelsesTidspunktUTC":"24-03-2026 15:01:59","Kommune":"Fredensborg","Kommunekode":210,"Afstemningsområde":"Karlebo","AfstemningsområdeDagiId":"700760","AfstemningsområdeNummer":8,"Valgdeltagelse":[{"AntalStemmeberretigedeVælgere":950,"AfgivneStemmer":116,"Tidspunkt":"09:00:00"},{"AntalStemmeberretigedeVælgere":950,"AfgivneStemmer":169,"Tidspunkt":"10:00:00"},{"AntalStemmeberretigedeVælgere":950,"AfgivneStemmer":210,"Tidspunkt":"11:00:00"},{"AntalStemmeberretigedeVælgere":950,"AfgivneStemmer":250,"Tidspunkt":"12:00:00"},{"AntalStemmeberretigedeVælgere":950,"AfgivneStemmer":306,"Tidspunkt":"13:00:00"},{"AntalStemmeberretigedeVælgere":950,"AfgivneStemmer":340,"Tidspunkt":"14:00:00"},{"AntalStemmeberretigedeVælgere":950,"AfgivneStemmer":387,"Tidspunkt":"15:00:00"},{"AntalStemmeberretigedeVælgere":950,"AfgivneStemmer":478,"Tidspunkt":"16:00:00"}]}

=== deterherligt/valg-data/folketingsvalg-135-24-03-2026/valgdeltagelse/valgdeltagelse-Folketingsvalg-Rødovre_Kommune-Valhøj-240320261802.json
{"Valgart":"Folketingsvalg","Valgdag":"24-03-2026","FrigivelsesTidspunktUTC":"24-03-2026 18:02:34","Kommune":"Rødovre","Kommunekode":175,"Afstemningsområde":"Valhøj","AfstemningsområdeDagiId":"707814","AfstemningsområdeNummer":4,"Valgdeltagelse":[{"AntalStemmeberretigedeVælgere":3805,"AfgivneStemmer":447,"Tidspunkt":"09:03:00"},{"AntalStemmeberretigedeVælgere":3805,"AfgivneStemmer":590,"Tidspunkt":"10:05:00"},{"AntalStemmeberretigedeVælgere":3805,"AfgivneStemmer":774,"Tidspunkt":"11:03:00"},{"AntalStemmeberretigedeVælgere":3805,"AfgivneStemmer":1007,"Tidspunkt":"12:03:00"},{"AntalStemmeberretigedeVælgere":3805,"AfgivneStemmer":1135,"Tidspunkt":"13:00:00"},{"AntalStemmeberretigedeVælgere":3805,"AfgivneStemmer":1518,"Tidspunkt":"14:01:00"},{"AntalStemmeberretigedeVælgere":3805,"AfgivneStemmer":1521,"Tidspunkt":"15:02:00"},{"AntalStemmeberretigedeVælgere":3805,"AfgivneStemmer":1832,"Tidspunkt":"16:01:00"},{"AntalStemmeberretigedeVælgere":3805,"AfgivneStemmer":2158,"Tidspunkt":"17:00:00"},{"AntalStemmeberretigedeVælgere":3805,"AfgivneStemmer":2470,"Tidspunkt":"18:00:00"},{"AntalStemmeberretigedeVælgere":3805,"AfgivneStemmer":2698,"Tidspunkt":"19:02:00"}]}
