=== deterherligt/valg-data/folketingsvalg-135-24-03-2026/Snitfladebeskrivelser/Valgdeltagelse/Valgdeltagelse.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Valgdeltagelse",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "Valgart",
    "Valgdag",
    "FrigivelsesTidspunktUTC",
    "Kommune",
    "Kommunekode",
    "Afstemningsområde",
    "AfstemningsområdeDagiId",
    "AfstemningsområdeNummer",
    "Valgdeltagelse"
  ],
  "properties": {
    "Valgart": {
      "type": "string",
      "description": "Navn på valget fx.: Folketingsvalg."
    },
    "Valgdag": {
      "type": "string",
      "description": "Dato for valget",
      "format": "date",
      "pattern": "^(0[1-9]|[12][0-9]|3[01])-(0[1-9]|1[0-2])-(\\d{4})$"
    },
    "FrigivelsesTidspunktUTC": {
      "type": "string",
      "description": "UTC DateTime for filens oprettelse.",
      "format": "date-time",
      "pattern": "^(0[1-9]|[12][0-9]|3[01])-(0[1-9]|1[0-2])-(\\d{4}) (0[0-9]|1[0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9])$"
    },
    "Kommune": {
      "type": "string",
      "description": "Navn på kommunen"
    },
    "Kommunekode": {
      "type": "integer",
      "description": "Kode på kommunen",
      "format": "int32"
    },
    "Afstemningsområde": {
      "type": "string",
      "description": "Navn på afstemningsområde"
    },
    "AfstemningsområdeDagiId": {
      "type": "string",
      "description": "Afstemningsområde Id i DAGI"
    },
    "AfstemningsområdeNummer": {
      "type": "integer",
      "description": "Nummeret på afstemningsområdet",
      "format": "int32"
    },
    "Valgdeltagelse": {
      "type": "array",
      "description": "Indeholder en liste af Valgdeltagelse objekter.",
      "items": {
        "$ref": "#/definitions/Valgdeltagelse"
      }
    }
  },
  "definitions": {
    "Valgdeltagelse": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "AntalStemmeberretigedeVælgere",
        "AfgivneStemmer",
        "Tidspunkt"
      ],
      "properties": {
        "AntalStemmeberretigedeVælgere": {
          "type": "integer",
          "description": "Antallet på stemmeberettigede vælgere",
          "format": "int32"
        },
        "AfgivneStemmer": {
          "type": "integer",
          "description": "Antallet af afgivne stemmer",
          "format": "int32"
        },
        "Tidspunkt": {
          "type": "string",
          "description": "Tidspunktet for hvornår denne valgdeltagelse blev registreret på formatet: tt:mm.",
          "format": "time"
        }
      }
    }
  }
}

=== deterherligt/valg-data/folketingsvalg-135-24-03-2026/valgdeltagelse/valgdeltagelse-Folketingsvalg-Ikast-Brande_Kommune-Engesvang-240320261603.json
{"Valgart":"Folketingsvalg","Valgdag":"24-03-2026","FrigivelsesTidspunktUTC":"24-03-2026 16:03:20","Kommune":"Ikast-Brande","Kommunekode":756,"Afstemningsområde":"Engesvang","AfstemningsområdeDagiId":"713316","AfstemningsområdeNummer":4,"Valgdeltagelse":[{"AntalStemmeberretigedeVælgere":2279,"AfgivneStemmer":221,"Tidspunkt":"09:00:00"},{"AntalStemmeberretigedeVælgere":2279,"AfgivneStemmer":346,"Tidspunkt":"10:00:00"},{"AntalStemmeberretigedeVælgere":2279,"AfgivneStemmer":589,"Tidspunkt":"12:00:00"},{"AntalStemmeberretigedeVælgere":2279,"AfgivneStemmer":803,"Tidspunkt":"14:00:00"},{"AntalStemmeberretigedeVælgere":2279,"AfgivneStemmer":1135,"Tidspunkt":"16:00:00"},{"AntalStemmeberretigedeVælgere":2279,"AfgivneStemmer":1401,"Tidspunkt":"17:00:00"}]}

=== deterherligt/valg-data/folketingsvalg-135-24-03-2026/valgdeltagelse/valgdeltagelse-Folketingsvalg-Rudersdal_Kommune-Toftevang-240320261212.json
{"Valgart":"Folketingsvalg","Valgdag":"24-03-2026","FrigivelsesTidspunktUTC":"24-03-2026 12:12:48","Kommune":"Rudersdal","Kommunekode":230,"Afstemningsområde":"Toftevang","AfstemningsområdeDagiId":"705784","AfstemningsområdeNummer":6,"Valgdeltagelse":[{"AntalStemmeberretigedeVælgere":5619,"AfgivneStemmer":893,"Tidspunkt":"08:00:00"},{"AntalStemmeberretigedeVælgere":5619,"AfgivneStemmer":1238,"Tidspunkt":"09:00:00"},{"AntalStemmeberretigedeVælgere":5619,"AfgivneStemmer":1484,"Tidspunkt":"10:00:00"},{"AntalStemmeberretigedeVælgere":5619,"AfgivneStemmer":1758,"Tidspunkt":"11:00:00"},{"AntalStemmeberretigedeVælgere":5619,"AfgivneStemmer":2062,"Tidspunkt":"12:00:00"},{"AntalStemmeberretigedeVælgere":5619,"AfgivneStemmer":2327,"Tidspunkt":"13:00:00"}]}

=== deterherligt/valg-data/folketingsvalg-135-24-03-2026/valgdeltagelse/valgdeltagelse-Folketingsvalg-Lejre_Kommune-Rye-240320261304.json
{"Valgart":"Folketingsvalg","Valgdag":"24-03-2026","FrigivelsesTidspunktUTC":"24-03-2026 13:04:27","Kommune":"Lejre","Kommunekode":350,"Afstemningsområde":"Rye","AfstemningsområdeDagiId":"707756","AfstemningsområdeNummer":2,"Valgdeltagelse":[{"AntalStemmeberretigedeVælgere":2002,"AfgivneStemmer":240,"Tidspunkt":"09:00:00"},{"AntalStemmeberretigedeVælgere":2002,"AfgivneStemmer":357,"Tidspunkt":"10:00:00"},{"AntalStemmeberretigedeVælgere":2002,"AfgivneStemmer":480,"Tidspunkt":"11:00:00"},{"AntalStemmeberretigedeVælgere":2002,"AfgivneStemmer":634,"Tidspunkt":"12:00:00"},{"AntalStemmeberretigedeVælgere":2002,"AfgivneStemmer":746,"Tidspunkt":"13:00:00"},{"AntalStemmeberretigedeVælgere":2002,"AfgivneStemmer":847,"Tidspunkt":"14:00:00"}]}

=== deterherligt/valg-data/folketingsvalg-135-24-03-2026/valgdeltagelse/valgdeltagelse-Folketingsvalg-Middelfart_Kommune-Middelfart_Ø-240320261006.json
{"Valgart":"Folketingsvalg","Valgdag":"24-03-2026","FrigivelsesTidspunktUTC":"24-03-2026 10:06:31","Kommune":"Middelfart","Kommunekode":410,"Afstemningsområde":"Middelfart Ø","AfstemningsområdeDagiId":"708394","AfstemningsområdeNummer":2,"Valgdeltagelse":[{"AntalStemmeberretigedeVælgere":5628,"AfgivneStemmer":1143,"Tidspunkt":"10:00:00"}]}

=== deterherligt/valg-data/folketingsvalg-135-24-03-2026/valgdeltagelse/valgdeltagelse-Folketingsvalg-Lolland_Kommune-Birket-240320261310.json
{"Valgart":"Folketingsvalg","Valgdag":"24-03-2026","FrigivelsesTidspunktUTC":"24-03-2026 13:10:25","Kommune":"Lolland","Kommunekode":360,"Afstemningsområde":"Birket","AfstemningsområdeDagiId":"706808","AfstemningsområdeNummer":26,"Valgdeltagelse":[{"AntalStemmeberretigedeVælgere":341,"AfgivneStemmer":46,"Tidspunkt":"10:00:00"},{"AntalStemmeberretigedeVælgere":341,"AfgivneStemmer":124,"Tidspunkt":"12:00:00"},{"AntalStemmeberretigedeVælgere":341,"AfgivneStemmer":158,"Tidspunkt":"14:00:00"}]}

=== deterherligt/valg-data/folketingsvalg-135-24-03-2026/valgdeltagelse/valgdeltagelse-Folketingsvalg-Roskilde_Kommune-Svogerslev-240320261400.json
{"Valgart":"Folketingsvalg","Valgdag":"24-03-2026","FrigivelsesTidspunktUTC":"24-03-2026 14:00:32","Kommune":"Roskilde","Kommunekode":265,"Afstemningsområde":"Svogerslev","AfstemningsområdeDagiId":"705900","AfstemningsområdeNummer":7,"Valgdeltagelse":[{"AntalStemmeberretigedeVælgere":3331,"AfgivneStemmer":507,"Tidspunkt":"09:00:00"},{"AntalStemmeberretigedeVælgere":3331,"AfgivneStemmer":956,"Tidspunkt":"11:00:00"},{"AntalStemmeberretigedeVælgere":3331,"AfgivneStemmer":1346,"Tidspunkt":"13:00:00"},{"AntalStemmeberretigedeVælgere":3331,"AfgivneStemmer":1720,"Tidspunkt":"15:00:00"}]}

=== deterherligt/valg-data/folketingsvalg-135-24-03-2026/valgdeltagelse/valgdeltagelse-Folketingsvalg-Rebild_Kommune-Nørager-240320261703.json
{"Valgart":"Folketingsvalg","Valgdag":"24-03-2026","FrigivelsesTidspunktUTC":"24-03-2026 17:03:50","Kommune":"Rebild","Kommunekode":840,"Afstemningsområde":"Nørager","AfstemningsområdeDagiId":"712164","AfstemningsområdeNummer":5,"Valgdeltagelse":[{"AntalStemmeberretigedeVælgere":2117,"AfgivneStemmer":600,"Tidspunkt":"12:00:00"},{"AntalStemmeberretigedeVælgere":2117,"AfgivneStemmer":1504,"Tidspunkt":"18:00:00"}]}

=== deterherligt/valg-data/folketingsvalg-135-24-03-2026/valgdeltagelse/valgdeltagelse-Folketingsvalg-Københavns_Kommune-2__Øst-240320261726.json
{"Valgart":"Folketingsvalg","Valgdag":"24-03-2026","FrigivelsesTidspunktUTC":"24-03-2026 17:26:16","Kommune":"København","Kommunekode":101,"Afstemningsområde":"2. Øst","AfstemningsområdeDagiId":"725346","AfstemningsområdeNummer":57,"Valgdeltagelse":[{"AntalStemmeberretigedeVælgere":7486,"AfgivneStemmer":2634,"Tidspunkt":"12:00:00"},{"AntalStemmeberretigedeVælgere":7486,"AfgivneStemmer":4193,"Tidspunkt":"16:00:00"},{"AntalStemmeberretigedeVælgere":7486,"AfgivneStemmer":5541,"Tidspunkt":"18:00:00"}]}
